version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: chevereto-server_1
      APP_PORT: 8888

  server:
    image: chevereto/chevereto:latest
    container_name: chevereto-server
    user: "1000:1000"
    init: true
    environment:
      CHEVERETO_DB_HOST: chevereto-db
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_DB_USER: chevereto
      CHEVERETO_DB_PASS: chevereto
    volumes:
      - chevereto_data:/var/www/html
    depends_on:
      - chevereto-db
    restart: always

  chevereto-db:
    image: mysql:8.0
    container_name: chevereto-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chevereto
      MYSQL_USER: chevereto
      MYSQL_PASSWORD: chevereto
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  chevereto_data:
  db_data:
